server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.springcloud.pojo
  config-location:  classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#spring配置
spring:
  application:
    name: springcloud-provider-dept #三个服务名称一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 2019936206

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-hystrix-8001 #修改eureak上的默认描述信息
    prefer-ip-address: true #true,注册中心左下角可以看到ip地址
#info配置（actuator 完善监控信息,告知需要调用该服务的信息）
info:
  app.name: lk
  company: qtz.com

